# Generated by Django 5.1.6 on 2025-03-07 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('correo', models.CharField(max_length=100, verbose_name='Correo')),
                ('departamento', models.CharField(max_length=100, verbose_name='Departamento')),
                ('puesto', models.CharField(max_length=100, verbose_name='Puesto')),
                ('rol', models.IntegerField(choices=[(1, 'Administrador'), (2, 'Usuario'), (3, 'Invitado')], verbose_name='rol')),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
                ('estado', models.IntegerField(verbose_name='Estado')),
            ],
        ),
    ]
