# Generated by Django 5.1.6 on 2025-03-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='departamento',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.IntegerField(db_index=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='puesto',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Puesto'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.IntegerField(choices=[(1, 'Administrador'), (2, 'Usuario'), (3, 'Invitado')], db_index=True, verbose_name='rol'),
        ),
    ]
