# Generated by Django 5.1.6 on 2025-03-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0002_alter_usuario_correo_alter_usuario_departamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_equipo', models.CharField(db_index=True, max_length=100, verbose_name='Tipo')),
                ('serie', models.CharField(db_index=True, max_length=100, verbose_name='Serie')),
                ('marca', models.CharField(db_index=True, max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(db_index=True, max_length=100, verbose_name='Modelo')),
                ('observaciones', models.CharField(db_index=True, max_length=200, verbose_name='Observaciones')),
                ('estado', models.IntegerField(db_index=True, verbose_name='Estado')),
            ],
        ),
    ]
