# Generated by Django 5.1.6 on 2025-03-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0003_inventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='tipo_equipo',
            field=models.IntegerField(db_index=True, verbose_name='Tipo Equipo'),
        ),
    ]
