# Generated by Django 5.1.6 on 2025-03-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0004_alter_inventario_tipo_equipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleProcesos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Procesos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_solicitante', models.IntegerField(db_index=True, verbose_name='Solicitante')),
                ('id_responsable', models.IntegerField(db_index=True, verbose_name='Responsable')),
                ('id_recibioEquipo', models.IntegerField(db_index=True, verbose_name='Recibio Equipo')),
                ('id_autorizo', models.IntegerField(db_index=True, verbose_name='Autorizo')),
                ('id_autoriza_entrega', models.IntegerField(db_index=True, verbose_name='Autoriza Entrega')),
                ('fecha_inicio', models.DateField(db_index=True, verbose_name='Fecha Inicio')),
                ('fecha_fin', models.DateField(db_index=True, verbose_name='Fecha Fin')),
                ('fecha_regreso', models.DateField(db_index=True, verbose_name='Fecha Regreso')),
                ('estado', models.IntegerField(db_index=True, verbose_name='Estado')),
            ],
        ),
    ]
