# Generated by Django 5.1.6 on 2025-03-11 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0005_detalleprocesos_procesos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procesos',
            name='id_recibioEquipo',
        ),
    ]
