# Generated by Django 5.1.6 on 2025-03-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0007_detalleproceso_delete_detalleprocesos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(db_index=True, max_length=128, verbose_name='Password'),
        ),
    ]
