# Generated by Django 5.1.6 on 2025-03-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0008_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Password'),
        ),
    ]
