# Generated by Django 5.1.6 on 2025-03-12 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0011_usuario_is_active_usuario_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleproceso',
            name='id_inventario',
        ),
        migrations.RemoveField(
            model_name='detalleproceso',
            name='id_proceso',
        ),
        migrations.RemoveField(
            model_name='procesos',
            name='id_solicitante',
        ),
        migrations.AddField(
            model_name='detalleproceso',
            name='inventario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inv.inventario'),
        ),
        migrations.AddField(
            model_name='detalleproceso',
            name='proceso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inv.procesos'),
        ),
        migrations.AddField(
            model_name='procesos',
            name='descripcion',
            field=models.CharField(max_length=200, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='procesos',
            name='solicitante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitante', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procesos',
            name='tipo',
            field=models.CharField(max_length=20, null=True, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='procesos',
            name='ubicacion',
            field=models.CharField(max_length=200, null=True, verbose_name='ubicacion'),
        ),
    ]
