# Generated by Django 5.1.6 on 2025-03-12 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0012_remove_detalleproceso_id_inventario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procesos',
            name='id_responsable',
        ),
        migrations.AddField(
            model_name='procesos',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsable', to=settings.AUTH_USER_MODEL),
        ),
    ]
