# Generated by Django 5.1.6 on 2025-03-12 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0013_remove_procesos_id_responsable_procesos_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesos',
            name='fecha_regreso',
            field=models.DateField(db_index=True, null=True, verbose_name='Fecha Regreso'),
        ),
    ]
