# Generated by Django 5.1.6 on 2025-03-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0014_alter_procesos_fecha_regreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleproceso',
            name='id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
