# Generated by Django 5.1.6 on 2025-03-14 21:06

import inv.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0015_alter_detalleproceso_id_alter_procesos_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesos',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to=inv.models.guardar_documento),
        ),
    ]
