# Generated by Django 5.1.6 on 2025-03-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0017_alter_procesos_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesos',
            name='cantidad_dias',
            field=models.IntegerField(db_index=True, null=True, verbose_name='Cantidad de dias'),
        ),
        migrations.AlterField(
            model_name='procesos',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='temp/'),
        ),
    ]
