# Generated by Django 5.1.6 on 2025-03-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0018_procesos_cantidad_dias_alter_procesos_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='nombre_equipo',
            field=models.CharField(db_index=True, max_length=100, null=True, verbose_name='Nombre Equipo'),
        ),
    ]
